language: cpp

git:
  depth: 1

branches:
  only:
  - master
  - commonlib

jobs:
  fast_finish: true
  include:
  - name: Ubuntu CMake
    os: linux
    dist: bionic
    group: stable
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:beineri/opt-qt-5.14.2-bionic'
        update: true
        packages:
        - qt514base
        - qt514tools
        - gcc-9
        - g++-9
        - libc6-i386
        - libgl-dev
        - libgl1-mesa-dev
        - mesa-common-dev
    script:
        - PATH="/opt/qt514/bin:$PATH"
        - CXX="g++-9"
        - CC="gcc-9"
        - qt514-env.sh
        - mkdir ./build
        - cd ./build
        - cmake --version
        - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE ../
        - cmake --build .
        - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_DEBUG_POSTFIX=d ../
        - cmake --build .
  - name: Ubuntu QMake
    os: linux
    dist: bionic
    group: stable
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:beineri/opt-qt-5.14.2-bionic'
        update: true
        packages:
        - qt514base
        - qt514tools
        - gcc-9
        - g++-9
        - libc6-i386
        - libgl-dev
        - libgl1-mesa-dev
        - mesa-common-dev
    script:
        - PATH="/opt/qt514/bin:$PATH"
        - CXX="g++-9"
        - CC="gcc-9"
        - qt514-env.sh
        - qmake QtSimpleChat.pro
        - make
  - name: MacOS QMake
    os: osx
    osx_image: xcode11.3
    compiler: clang
    addons:
      homebrew:
        packages:
        - qt
        update: true
    script:
        - PATH="/usr/local/opt/qt5/bin:$PATH"
        - qmake QtSimpleChat.pro
        - make
  - name: MacOS CMake
    os: osx
    osx_image: xcode11.3
    compiler: clang
    addons:
      homebrew:
        packages:
        - qt
        update: true
    script:
        - PATH="/usr/local/opt/qt5/bin:$PATH"
        - mkdir ./build
        - cd ./build
        - cmake --version
        - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE ../
        - cmake --build .
        - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_DEBUG_POSTFIX=d ../
        - cmake --build .
notifications:
  email: false
